# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ 6.x.x ]
  pull_request:
    branches: [ 6.x.x ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8.0.192, 8 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }} 
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }} 
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
